### ISSUE TITLE
cancellation_source::request_cancellation()

### ISSUE THREAD

**Issue by bizehao** [Garcia6l20/cppcoro-http#1]
He can't work under Linux. I tried to solve it, but I couldn't find a way. Please, I need this in my project.

TEST(timer) {
    using namespace std::literals::chrono_literals;

    cppcoro::io_service ioService;

    cppcoro::cancellation_source source;

    cppcoro::sync_wait(cppcoro::when_all(
            [&]() -> cppcoro::task<> {
                try{
                    co_await ioService.schedule_after(2000ms,source.token());
                }catch(const std::exception& e){
                    std::cout << e.what() <<  std::endl;
                }
                std::cout << "00000" << std::endl;
            }(), [&]() -> cppcoro::task<> {
                co_await ioService.schedule_after(1000ms);
                source.request_cancellation();
            }(), [&]() -> cppcoro::task<> {
                ioService.process_events();
                co_return;
            }()

    ));
}

**Comment by bizehao** [comment]
I use a cpp compiler is clang11

**Comment by Garcia6l20** [comment]
Hi,

This does not seem to be related to cppcoro-http but only cppcoro.

Anyway, If you are using my fork you should be able to use it on linux with liburing.
This will only work with linux kernel >= 5.4, check it with `uname -r`, and if you want to use network/file IOs it will require kernel version >= 5.6.

1. Clone my fork (io_ring branch):
    ```bash
    git clone https://github.com/Garcia6l20/cppcoro.git
    git switch io_ring
    ```
2. Configure an install it (with liburing enabled and using clang-libc++):
    ```bash
    mkdir build && cd build
    cmake -DCMAKE_CXX_FLAGS="-stdlib=libc++" -DCPPCORO_USE_IO_RING=ON ..
    make && make install
    ```

**Comment by bizehao** [comment]
yes, I'm using it of your fork version,Nothing else is a problem, but the above piece of code runs with errors, win is normal, and there is a problem under Linux

**Comment by bizehao** [comment]
hi, I just solved it, I think since it's ECANCELED, there's no need to restore it, so I'm not going to resume it if I judge ECANCELED in the schedule.

io_service.cpp

this is my modification:
if (message != nullptr && message->resume != nullptr && message->result != -ECANCELED)

It's yours:
 if (message != nullptr && message->resume != nullptr)

**Comment by Garcia6l20** [comment]
Ok, I just tested it, and the ECANCELED is fired twice.

Thanks for reporting this issue.

I was wrongly removing the timeout and triggering a nop operation, which one was triggering the second process_event for this coro.

I just pushed a fix, tell me if it works for you, thanks again.

I modified your test body like this, to stop the program after cancellation:
```cpp
cppcoro::sync_wait(cppcoro::when_all(
    [&]() -> cppcoro::task<> {
      auto _ = cppcoro::on_scope_exit([&] {
         ioService.stop(); // stop io_service
       });
       try{
          co_await ioService.schedule_after(2000ms,source.token());
       } catch(const std::exception& e){
          std::cout << e.what() <<  std::endl;
       }
       std::cout << "00000" << std::endl;
     }(), [&]() -> cppcoro::task<> {
       co_await ioService.schedule_after(1000ms);
       source.request_cancellation();
     }(), [&]() -> cppcoro::task<> {
       ioService.process_events();
       co_return;
     }()
));
```

**Comment by bizehao** [comment]
nice! It is very good after implementation, thank you for your contribution, I have used it on my Raspberry Pi, really thank you!

**Comment by Garcia6l20** [comment]
Hi,
I've just rebased my work on top of https://github.com/andreasbuhr/cppcoro and found that the change maid here does not work in all cases.
I please stop using io_ring branch since I'll re-use it for CI purpose, use the master one which now contains the good fix.
Thanks again

**Comment by bizehao** [comment]
ok,I will try it  later.

**Comment by bizehao** [comment]
<pre>
#if CPPCORO_OS_LINUX
    m_cancellationRegistration.emplace(std::move(m_cancellationToken), [&service, this] {
        service.io_queue().transaction(m_message).timeout_remove().commit();
    });
#endif
 </pre>
Isn't that less

``m_message.result = -ECANCELED;``

It's normal after I add it
